main

diff --git a/demos/qke/qbot b/demos/qke/qbot
--- a/demos/qke/qbot
+++ b/demos/qke/qbot
@@ -58,9 +58,15 @@ DEMO_PROMPT="\e[0;38;5;231;48;5;31;1m (qb) \e[0;38;5;31;48;5;236;22m \e[0;38;
 # hide the evidence
 #clear
 printf "\033c"
-alias qbo=cli
+CLI_IMAGE=levitas/cli:latest
+if [ -f /.dockerenv ]; then
+        alias qbo=cli
+else
+        alias qbo="docker run --rm --name qbo-cli -e QBO_HOST=$QBO_HOST -e QBO_PORT=$QBO_PORT -e QBO_UID=$QBO_UID -e QBO_AUX=$QBO_AUX --network host -i -v ~/.qbo:/tmp/qbo $CLI_IMAGE cli"
+fi
 
 pe "qbo version | jq .version[]?"
+#pe "qbo get node $NAME | jq -r '.nodes[]? | select( .name | contains(\"node-\")) | .name' | tail -1"
 # ADD CLUSTER
 pe "qbo add cluster $NAME | jq"
 pe "qbo get nodes $NAME | jq '.nodes[]?'"
@@ -96,24 +102,28 @@ if [ "$V" = "ce" ]; then
 	pe "watch kubectl get pods -n kube-system"
 fi
 
-# STOP CLUSTER
-NODE=$(qbo get node alex | jq -r .nodes[]?.name | head -1)
-pe "qbo stop node $NODE | jq"
-if [ "$V" = "ce" ]; then
-	pe "watch kubectl get nodes"
+# STOP NODE
+pe "qbo get node $NAME | jq -r '.nodes[]? | select( .name | contains(\"node-\")) | .name' | tail -1"
+NODE=$(qbo get node $NAME | jq -r '.nodes[]? | select( .name | contains("node-")) | .name' | tail -1)
+if [ -z $NODE ]; then
+        echo "node can't be found"
+        exit 1
 fi
+pe "qbo stop node $NODE | jq"
+#if [ "$V" = "ce" ]; then
+pe "watch kubectl get nodes"
+#fi
 # START NODE
 pe "qbo start node $NODE | jq"
-if [ "$V" = "ce" ]; then
-	pe "watch kubectl get nodes"
-        pe "watch kubectl get pods -n kube-system"
-fi
-
+#if [ "$V" = "ce" ]; then
+pe "watch kubectl get nodes"
+#        pe "watch kubectl get pods -n kube-system"
+#fi
 # DELETE NODE
 pe "qbo delete node $NODE | jq"
-if [ "$V" = "ce" ]; then
-	pe "watch kubectl get nodes"
-fi
+#if [ "$V" = "ce" ]; then
+pe "watch kubectl get nodes"
+#fi
 # DELETE CLUSTER
 pe "qbo delete cluster $NAME | jq"
 
